<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyArt.DataAccess\MyArt.DataAccess.csproj" />
    <ProjectReference Include="..\MyArt.Models\MyArt.Models.csproj" />
    <ProjectReference Include="..\MyArt.Utility\MyArt.Utility.csproj" />
  </ItemGroup>

</Project>
