// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyArt.Web.Data;

#nullable disable

namespace MyArt.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908114320_SeedingDefaultRolesandUser")]
    partial class SeedingDefaultRolesandUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f79a0806-0bc2-4d7f-b4c4-19263f08583a",
                            ConcurrencyStamp = "28b70e8c-2f9b-4083-a819-d308486a3322",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b3a56ae8-7969-4e4a-8902-01ae516f78a0",
                            ConcurrencyStamp = "d431deca-b4d6-42f6-8648-74194a57c2fa",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c1a2b3c4-d5e6-7f8g-9h0i-j1k2l3m4n5o6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a169f119-b98d-4654-92f3-f7fc21876d86",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELE8YG/cosuBH+OOPPWHcDIuTS+r1q1WUoYzF0BZBb2yEPGQe8+q7rU3wxf56838+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1d172a2-a61d-4437-a14e-7d2741823640",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c1a2b3c4-d5e6-7f8g-9h0i-j1k2l3m4n5o6",
                            RoleId = "f79a0806-0bc2-4d7f-b4c4-19263f08583a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyArt.Web.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "",
                            LastName = "Banksy",
                            PlaceOfBirth = "Yate (UK)",
                            YearOfBirth = "1974"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Gerrit",
                            LastName = "Baten",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1959"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Etienne",
                            LastName = "Bauwens",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1930"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Geert",
                            LastName = "Bauwens",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1961"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "René",
                            LastName = "Bekaert",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1938"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "André",
                            LastName = "Berner",
                            PlaceOfBirth = "Vilvoorde",
                            YearOfBirth = "1955"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Walter",
                            LastName = "Brems",
                            PlaceOfBirth = "Reet",
                            YearOfBirth = "1947"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Pedro",
                            LastName = "Brugada",
                            PlaceOfBirth = "Girona (ESP)",
                            YearOfBirth = "1952"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "André",
                            LastName = "Bruylandt",
                            PlaceOfBirth = "Onkerzele",
                            YearOfBirth = "1944"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Randall",
                            LastName = "Casaer",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Roland",
                            LastName = "Cobbaut",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1961"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Claire",
                            LastName = "Cocquyt",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Raf",
                            LastName = "Coorevits",
                            PlaceOfBirth = "Sint-Niklaas",
                            YearOfBirth = "1934"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Tony",
                            LastName = "De Bruycker",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1950"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Vigdis",
                            LastName = "De Cauter",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1974"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Jeanne",
                            LastName = "De Dijn",
                            PlaceOfBirth = "Wichelen",
                            YearOfBirth = "1919"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Robert",
                            LastName = "De keersmaecker",
                            PlaceOfBirth = "Bornem",
                            YearOfBirth = "1955"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Luc",
                            LastName = "De Mot",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1934"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Pieter",
                            LastName = "De Poortere",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1976"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Gino",
                            LastName = "Dermaut",
                            PlaceOfBirth = "Roeselare",
                            YearOfBirth = "1951"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Paul",
                            LastName = "De Ryck",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1953"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Jozef",
                            LastName = "De Schrijver",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1916"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "François",
                            LastName = "Deshommes",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1939"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Theo",
                            LastName = "De Smedt",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1938"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Leen",
                            LastName = "De Vos",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1952"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Frans",
                            LastName = "De Vree",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1934"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Paul",
                            LastName = "De Vylder",
                            PlaceOfBirth = "Sint-Niklaas",
                            YearOfBirth = "1942"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Ignace",
                            LastName = "Dierickx",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Hans",
                            LastName = "Droesbeke",
                            PlaceOfBirth = "Geraardsbergen",
                            YearOfBirth = "1968"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Ronald",
                            LastName = "Ergo",
                            PlaceOfBirth = "Watervliet",
                            YearOfBirth = "1936"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "",
                            LastName = "Expha",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Leonor",
                            LastName = "Fini",
                            PlaceOfBirth = "Buenos Aires (ARG)",
                            YearOfBirth = "1907"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Rafaël",
                            LastName = "Gorsen",
                            PlaceOfBirth = "Merksem",
                            YearOfBirth = "1942"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Daniël",
                            LastName = "Hardyns",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1951"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Henri",
                            LastName = "Hemelsoet",
                            PlaceOfBirth = "Westdorpe (NL)",
                            YearOfBirth = "1955"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Eveline",
                            LastName = "Henderickx",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1931"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Carla",
                            LastName = "Heuvinck",
                            PlaceOfBirth = "",
                            YearOfBirth = ""
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Luc",
                            LastName = "Hoenraet",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1941"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Achiel",
                            LastName = "Hutsebaut",
                            PlaceOfBirth = "Hofstade",
                            YearOfBirth = "1936"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Octave",
                            LastName = "Landuyt",
                            PlaceOfBirth = "Gent",
                            YearOfBirth = "1922"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Fons",
                            LastName = "Macharis",
                            PlaceOfBirth = "Denderbelle",
                            YearOfBirth = "1927"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Mik",
                            LastName = "Maes",
                            PlaceOfBirth = "Aalst",
                            YearOfBirth = "1959"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "",
                            LastName = "MarieAnge",
                            PlaceOfBirth = "Nieuwpoort",
                            YearOfBirth = "1963"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Frans",
                            LastName = "Minnaert",
                            PlaceOfBirth = "Idegem",
                            YearOfBirth = "1929"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Geert",
                            LastName = "Opsomer",
                            PlaceOfBirth = "Waregem",
                            YearOfBirth = "1958"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Wilhelm",
                            LastName = "Mechnig",
                            PlaceOfBirth = "Köln (GER)",
                            YearOfBirth = "1929"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Achiel",
                            LastName = "Pauwels",
                            PlaceOfBirth = "Mariakerke",
                            YearOfBirth = "1932"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Dany",
                            LastName = "Persoons",
                            PlaceOfBirth = "Aspelare",
                            YearOfBirth = "1938"
                        });
                });

            modelBuilder.Entity("MyArt.Web.Models.Technic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acryl"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aquarel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aquarel & fineliner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aquatint"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bister"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Balpen & markers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cement"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ets"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ets, droge naald"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gemengde techniek"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gouache"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Houtsnede"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Keramiek"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Klei"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kleurpotlood"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Linosnede"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Litho"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Offset druk"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Olieverf"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Oostindische inkt"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Opgehoogde zeefdruk"
                        },
                        new
                        {
                            Id = 22,
                            Name = "PC grafiek"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Print op doek"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Print op fotopapier"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
